package command;

import EncryptionFunctions.InformationProcessing;

public class GenerateSeedCommand implements Command {
    public String name() {
        return "-gs";
    }

    public String description() {
        return "Generates a random seed for encryption/decryption";
    }

    public void execute(String[] args) {
        int autoSeed = Integer.parseInt(args[0].trim());
        int[][] generatedSeed = InformationProcessing.autoSeedGenerate(autoSeed);
        String generatedSeedString = InformationProcessing.autoGeneratedSeedToString(generatedSeed);
        System.out.println("Generated Seed: " + generatedSeedString);
    }

    @Override
    public String secondaryName() {
        return "--generate-seed";
    }

}
